# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = ./

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = ./

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/jwmil/MillerInc.GPU/PhysicsEngine/CMakeFiles /mnt/c/Users/jwmil/MillerInc.GPU/PhysicsEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/jwmil/MillerInc.GPU/PhysicsEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhysicsEngine

# Build rule for target.
PhysicsEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhysicsEngine
.PHONY : PhysicsEngine

# fast build rule for target.
PhysicsEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/build
.PHONY : PhysicsEngine/fast

source/FieldTypes/BaseTypes/Vector3.o: source/FieldTypes/BaseTypes/Vector3.cpp.o
.PHONY : source/FieldTypes/BaseTypes/Vector3.o

# target to build an object file
source/FieldTypes/BaseTypes/Vector3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/BaseTypes/Vector3.cpp.o
.PHONY : source/FieldTypes/BaseTypes/Vector3.cpp.o

source/FieldTypes/BaseTypes/Vector3.i: source/FieldTypes/BaseTypes/Vector3.cpp.i
.PHONY : source/FieldTypes/BaseTypes/Vector3.i

# target to preprocess a source file
source/FieldTypes/BaseTypes/Vector3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/BaseTypes/Vector3.cpp.i
.PHONY : source/FieldTypes/BaseTypes/Vector3.cpp.i

source/FieldTypes/BaseTypes/Vector3.s: source/FieldTypes/BaseTypes/Vector3.cpp.s
.PHONY : source/FieldTypes/BaseTypes/Vector3.s

# target to generate assembly for a file
source/FieldTypes/BaseTypes/Vector3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/BaseTypes/Vector3.cpp.s
.PHONY : source/FieldTypes/BaseTypes/Vector3.cpp.s

source/FieldTypes/ComplexTypes/ContactForce.o: source/FieldTypes/ComplexTypes/ContactForce.cpp.o
.PHONY : source/FieldTypes/ComplexTypes/ContactForce.o

# target to build an object file
source/FieldTypes/ComplexTypes/ContactForce.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/ComplexTypes/ContactForce.cpp.o
.PHONY : source/FieldTypes/ComplexTypes/ContactForce.cpp.o

source/FieldTypes/ComplexTypes/ContactForce.i: source/FieldTypes/ComplexTypes/ContactForce.cpp.i
.PHONY : source/FieldTypes/ComplexTypes/ContactForce.i

# target to preprocess a source file
source/FieldTypes/ComplexTypes/ContactForce.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/ComplexTypes/ContactForce.cpp.i
.PHONY : source/FieldTypes/ComplexTypes/ContactForce.cpp.i

source/FieldTypes/ComplexTypes/ContactForce.s: source/FieldTypes/ComplexTypes/ContactForce.cpp.s
.PHONY : source/FieldTypes/ComplexTypes/ContactForce.s

# target to generate assembly for a file
source/FieldTypes/ComplexTypes/ContactForce.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/ComplexTypes/ContactForce.cpp.s
.PHONY : source/FieldTypes/ComplexTypes/ContactForce.cpp.s

source/FieldTypes/ComplexTypes/Force.o: source/FieldTypes/ComplexTypes/Force.cpp.o
.PHONY : source/FieldTypes/ComplexTypes/Force.o

# target to build an object file
source/FieldTypes/ComplexTypes/Force.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/ComplexTypes/Force.cpp.o
.PHONY : source/FieldTypes/ComplexTypes/Force.cpp.o

source/FieldTypes/ComplexTypes/Force.i: source/FieldTypes/ComplexTypes/Force.cpp.i
.PHONY : source/FieldTypes/ComplexTypes/Force.i

# target to preprocess a source file
source/FieldTypes/ComplexTypes/Force.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/ComplexTypes/Force.cpp.i
.PHONY : source/FieldTypes/ComplexTypes/Force.cpp.i

source/FieldTypes/ComplexTypes/Force.s: source/FieldTypes/ComplexTypes/Force.cpp.s
.PHONY : source/FieldTypes/ComplexTypes/Force.s

# target to generate assembly for a file
source/FieldTypes/ComplexTypes/Force.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/FieldTypes/ComplexTypes/Force.cpp.s
.PHONY : source/FieldTypes/ComplexTypes/Force.cpp.s

source/PhysicsEngine/Scenes/Scene.o: source/PhysicsEngine/Scenes/Scene.cpp.o
.PHONY : source/PhysicsEngine/Scenes/Scene.o

# target to build an object file
source/PhysicsEngine/Scenes/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsEngine/Scenes/Scene.cpp.o
.PHONY : source/PhysicsEngine/Scenes/Scene.cpp.o

source/PhysicsEngine/Scenes/Scene.i: source/PhysicsEngine/Scenes/Scene.cpp.i
.PHONY : source/PhysicsEngine/Scenes/Scene.i

# target to preprocess a source file
source/PhysicsEngine/Scenes/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsEngine/Scenes/Scene.cpp.i
.PHONY : source/PhysicsEngine/Scenes/Scene.cpp.i

source/PhysicsEngine/Scenes/Scene.s: source/PhysicsEngine/Scenes/Scene.cpp.s
.PHONY : source/PhysicsEngine/Scenes/Scene.s

# target to generate assembly for a file
source/PhysicsEngine/Scenes/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsEngine/Scenes/Scene.cpp.s
.PHONY : source/PhysicsEngine/Scenes/Scene.cpp.s

source/PhysicsObjects/BaseObject.o: source/PhysicsObjects/BaseObject.cpp.o
.PHONY : source/PhysicsObjects/BaseObject.o

# target to build an object file
source/PhysicsObjects/BaseObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/BaseObject.cpp.o
.PHONY : source/PhysicsObjects/BaseObject.cpp.o

source/PhysicsObjects/BaseObject.i: source/PhysicsObjects/BaseObject.cpp.i
.PHONY : source/PhysicsObjects/BaseObject.i

# target to preprocess a source file
source/PhysicsObjects/BaseObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/BaseObject.cpp.i
.PHONY : source/PhysicsObjects/BaseObject.cpp.i

source/PhysicsObjects/BaseObject.s: source/PhysicsObjects/BaseObject.cpp.s
.PHONY : source/PhysicsObjects/BaseObject.s

# target to generate assembly for a file
source/PhysicsObjects/BaseObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/BaseObject.cpp.s
.PHONY : source/PhysicsObjects/BaseObject.cpp.s

source/PhysicsObjects/Collidables/CollisionObject.o: source/PhysicsObjects/Collidables/CollisionObject.cpp.o
.PHONY : source/PhysicsObjects/Collidables/CollisionObject.o

# target to build an object file
source/PhysicsObjects/Collidables/CollisionObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/CollisionObject.cpp.o
.PHONY : source/PhysicsObjects/Collidables/CollisionObject.cpp.o

source/PhysicsObjects/Collidables/CollisionObject.i: source/PhysicsObjects/Collidables/CollisionObject.cpp.i
.PHONY : source/PhysicsObjects/Collidables/CollisionObject.i

# target to preprocess a source file
source/PhysicsObjects/Collidables/CollisionObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/CollisionObject.cpp.i
.PHONY : source/PhysicsObjects/Collidables/CollisionObject.cpp.i

source/PhysicsObjects/Collidables/CollisionObject.s: source/PhysicsObjects/Collidables/CollisionObject.cpp.s
.PHONY : source/PhysicsObjects/Collidables/CollisionObject.s

# target to generate assembly for a file
source/PhysicsObjects/Collidables/CollisionObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/CollisionObject.cpp.s
.PHONY : source/PhysicsObjects/Collidables/CollisionObject.cpp.s

source/PhysicsObjects/Collidables/ImpulseObject.o: source/PhysicsObjects/Collidables/ImpulseObject.cpp.o
.PHONY : source/PhysicsObjects/Collidables/ImpulseObject.o

# target to build an object file
source/PhysicsObjects/Collidables/ImpulseObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/ImpulseObject.cpp.o
.PHONY : source/PhysicsObjects/Collidables/ImpulseObject.cpp.o

source/PhysicsObjects/Collidables/ImpulseObject.i: source/PhysicsObjects/Collidables/ImpulseObject.cpp.i
.PHONY : source/PhysicsObjects/Collidables/ImpulseObject.i

# target to preprocess a source file
source/PhysicsObjects/Collidables/ImpulseObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/ImpulseObject.cpp.i
.PHONY : source/PhysicsObjects/Collidables/ImpulseObject.cpp.i

source/PhysicsObjects/Collidables/ImpulseObject.s: source/PhysicsObjects/Collidables/ImpulseObject.cpp.s
.PHONY : source/PhysicsObjects/Collidables/ImpulseObject.s

# target to generate assembly for a file
source/PhysicsObjects/Collidables/ImpulseObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/ImpulseObject.cpp.s
.PHONY : source/PhysicsObjects/Collidables/ImpulseObject.cpp.s

source/PhysicsObjects/Collidables/SimpleShapes/Cube.o: source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.o
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Cube.o

# target to build an object file
source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.o
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.o

source/PhysicsObjects/Collidables/SimpleShapes/Cube.i: source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.i
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Cube.i

# target to preprocess a source file
source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.i
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.i

source/PhysicsObjects/Collidables/SimpleShapes/Cube.s: source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.s
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Cube.s

# target to generate assembly for a file
source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.s
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Cube.cpp.s

source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.o: source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.o
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.o

# target to build an object file
source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.o
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.o

source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.i: source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.i
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.i

# target to preprocess a source file
source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.i
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.i

source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.s: source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.s
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.s

# target to generate assembly for a file
source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.s
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.cpp.s

source/PhysicsObjects/Collidables/SimpleShapes/Sphere.o: source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.o
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Sphere.o

# target to build an object file
source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.o
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.o

source/PhysicsObjects/Collidables/SimpleShapes/Sphere.i: source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.i
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Sphere.i

# target to preprocess a source file
source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.i
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.i

source/PhysicsObjects/Collidables/SimpleShapes/Sphere.s: source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.s
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Sphere.s

# target to generate assembly for a file
source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.s
.PHONY : source/PhysicsObjects/Collidables/SimpleShapes/Sphere.cpp.s

source/Rendering/Windows/CPU/visualizer.o: source/Rendering/Windows/CPU/visualizer.cpp.o
.PHONY : source/Rendering/Windows/CPU/visualizer.o

# target to build an object file
source/Rendering/Windows/CPU/visualizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/Rendering/Windows/CPU/visualizer.cpp.o
.PHONY : source/Rendering/Windows/CPU/visualizer.cpp.o

source/Rendering/Windows/CPU/visualizer.i: source/Rendering/Windows/CPU/visualizer.cpp.i
.PHONY : source/Rendering/Windows/CPU/visualizer.i

# target to preprocess a source file
source/Rendering/Windows/CPU/visualizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/Rendering/Windows/CPU/visualizer.cpp.i
.PHONY : source/Rendering/Windows/CPU/visualizer.cpp.i

source/Rendering/Windows/CPU/visualizer.s: source/Rendering/Windows/CPU/visualizer.cpp.s
.PHONY : source/Rendering/Windows/CPU/visualizer.s

# target to generate assembly for a file
source/Rendering/Windows/CPU/visualizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/Rendering/Windows/CPU/visualizer.cpp.s
.PHONY : source/Rendering/Windows/CPU/visualizer.cpp.s

source/library.o: source/library.cpp.o
.PHONY : source/library.o

# target to build an object file
source/library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/library.cpp.o
.PHONY : source/library.cpp.o

source/library.i: source/library.cpp.i
.PHONY : source/library.i

# target to preprocess a source file
source/library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/library.cpp.i
.PHONY : source/library.cpp.i

source/library.s: source/library.cpp.s
.PHONY : source/library.s

# target to generate assembly for a file
source/library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/source/library.cpp.s
.PHONY : source/library.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PhysicsEngine"
	@echo "... source/FieldTypes/BaseTypes/Vector3.o"
	@echo "... source/FieldTypes/BaseTypes/Vector3.i"
	@echo "... source/FieldTypes/BaseTypes/Vector3.s"
	@echo "... source/FieldTypes/ComplexTypes/ContactForce.o"
	@echo "... source/FieldTypes/ComplexTypes/ContactForce.i"
	@echo "... source/FieldTypes/ComplexTypes/ContactForce.s"
	@echo "... source/FieldTypes/ComplexTypes/Force.o"
	@echo "... source/FieldTypes/ComplexTypes/Force.i"
	@echo "... source/FieldTypes/ComplexTypes/Force.s"
	@echo "... source/PhysicsEngine/Scenes/Scene.o"
	@echo "... source/PhysicsEngine/Scenes/Scene.i"
	@echo "... source/PhysicsEngine/Scenes/Scene.s"
	@echo "... source/PhysicsObjects/BaseObject.o"
	@echo "... source/PhysicsObjects/BaseObject.i"
	@echo "... source/PhysicsObjects/BaseObject.s"
	@echo "... source/PhysicsObjects/Collidables/CollisionObject.o"
	@echo "... source/PhysicsObjects/Collidables/CollisionObject.i"
	@echo "... source/PhysicsObjects/Collidables/CollisionObject.s"
	@echo "... source/PhysicsObjects/Collidables/ImpulseObject.o"
	@echo "... source/PhysicsObjects/Collidables/ImpulseObject.i"
	@echo "... source/PhysicsObjects/Collidables/ImpulseObject.s"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/Cube.o"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/Cube.i"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/Cube.s"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.o"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.i"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/FlatSheet.s"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/Sphere.o"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/Sphere.i"
	@echo "... source/PhysicsObjects/Collidables/SimpleShapes/Sphere.s"
	@echo "... source/Rendering/Windows/CPU/visualizer.o"
	@echo "... source/Rendering/Windows/CPU/visualizer.i"
	@echo "... source/Rendering/Windows/CPU/visualizer.s"
	@echo "... source/library.o"
	@echo "... source/library.i"
	@echo "... source/library.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

