name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install CMake
        run: sudo apt-get install cmake

#      - name: Install CUDA
#        run: sudo apt-get install nvidia-cuda-toolkit

      - name: Set up permissions for configure script
        run: chmod +x ./configure

      #- name: configure
      #  run: ./configure

      - name: Setup PhysicsEngine
        run: cmake .

      - name: Build PhysicsEngine library
        run: make

#      - name: Build PhysicsEngineGPU
#        run: cmake -S . -B cmake-build-release-wsl -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=/usr/bin/g++
#          -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc

#      - name: Archive static library
#        if: success()
#        run: mkdir -p artifacts && sudo cp ./libPhysicsEngine.a artifacts/

#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: static-library
#          path: artifacts/